### ISSUE TITLE
What is the deal with Whisper?!

### ISSUE THREAD

**Issue by stnbu** [gballet/whisper-chat-example#12]
Hello, Friend. I thought I'd take a chance and try abusing this repo's issues feature to see if I can figure out what happened to Whisper and/or this project.

Sorry in advance.

This project is exactly what I had in mind when I found out about Whisper, Swarm (and all that). The fact that this (and this kind of thing) has not taken off like a rocket suggests to me that "something is up". It's such an obvious need, yet anything that uses Whisper seems to be semi-dead. I thought maybe @gballet (who no doubt is _very busy_) would know, given your involvement in all this threeish years ago.

Assuming it's still "a thing" I'm happy to compensate for my spamming by doing something useful, like trying to get this code to work in the current ecosystem. Or testing or whatever's needed.

In whatever case: have a great day!

**Comment by gballet** [comment]
Sorry for my late response, I didn't have notifications setup on this repo. Whisper is now deprecated and replaced by waku https://our.status.im/peer-to-peer-messaging-where-whisper-falls-short-and-waku-picks-up/ I'll be closing this issue and archiving that repository.
