### ISSUE TITLE
No whisper-chat-example.js file

### ISSUE THREAD

**Issue by Parthsahu15** [gballet/whisper-chat-example#4]
In index.html script is defined as "/dist/whisper-chat-example.js" but there is no dist folder and no whisper-chat-example.js file

**Comment by gballet** [comment]
Sorry for the late response, I didn't see the notification for your issue.

The file is generated by webpack [here](https://github.com/gballet/whisper-chat-example/blob/master/webpack.config.js#L9) and so in order to see it, you need to run webpack as explained in `README.md`.
