### ISSUE TITLE
Do I need 2 geth instances to have 2 parties chat with each other?

### ISSUE THREAD

**Issue by rairyx** [gballet/whisper-chat-example#7]
I tried to use the example with 2 users on 2 chat pages in the browser, tried both asymmetric key and symmetric key but it doesn't work. Do I need 2 geth instances to have 2 parties chat with each other?

**Comment by oleksandr-hk** [comment]
Hello) 

> I tried to use the example with 2 users on 2 chat pages in the browser, tried both asymmetric key and symmetric key but it doesn't work. Do I need 2 geth instances to have 2 parties chat with each other?

Did you find solution for this problem?

**Comment by rairyx** [comment]
Yes it works now with 2 chat pages in one browser and 1 geth instance, I didn't change anything. Sometimes not that stable with sym key. I'd like to try 2 geth instances on different devices
